apiVersion: v2
name: k8s-audit-metrics
version: 0.10.12
appVersion: 0.10.12
description: Collector that exposes metrics from k8s apiserver audit log.
home: "https://github.com/giantswarm/k8s-audit-metrics"
icon: https://s.giantswarm.io/app-icons/prometheus/1/light.svg
annotations:
  application.giantswarm.io/team: tenet
  io.giantswarm.application.team: tenet
